Repository quortex/terraform-aws-eks-cluster, pull requests merged in 2020-11, with the labels that each got.

#17 add support for private / public worker nodes
  README.md
  kubernetes.tf
  node_group_advanced.tf
  variables.tf
Labels: enhancement, good first issue

#19 Align Kubernetes version between master/worker defaults
  node_group_advanced.tf
  variables.tf
Labels: good first issue

#20 Add spot_instance_pools argument to advanced node groups
  README.md
  node_group_advanced.tf
Labels: bug, documentation, good first issue
